name: Go Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.25.3'
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: go build -o ./main .
      - name: Package
        run: |
          mkdir iot_orchestrator
          cp iot_orchestrator iot_orchestrator/
          cp integrations iot_orchestrator/ -rv
          cp apis iot_orchestrator/ -rv
          cp config.json iot_orchestrator/
          cp package*.json iot_orchestrator/
          mkdir iot_orchestrator/configs
          mkdir iot_orchestrator/schemas
          zip -r iot_orchestrator.zip iot_orchestrator
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iot_orchestrator
          path: ./iot_orchestrator.zip